### ISSUE TITLE
Need a example for reacting with Input from UI

### ISSUE THREAD

**Issue by XinMaAT** [DevExpress-Examples/Reporting-Blazor-Getting-Started#1]
is it possible offering an report example to react with UI input.

for example, something like a sum calculator, 
given two SpinEdit A and B, then click a preview button, then a sum shows in the Document Viewer.

Thanks a lot.

**Comment by vasyaste** [comment]
Hello @XinMaAT,

So, the main question is how to pass parameters from your UI elements to a report, am I correct? To accomplish this you can collect the values from UI editors and embed them into the value that is passed to the `ReportUrl` property of the viewer/designer control. Then in the server-side `GetData` method of the 'ReportStorage' class you can access the 'url' value that was sent by your UI and get the UI elements' values from this string. Then you can pass these values to your report by using the [Report Parameters](https://docs.devexpress.com/XtraReports/4812/detailed-guide-to-devexpress-reporting/shape-report-data/use-report-parameters) functionality. These parameters can be used to filter the report's data source.

P.S. If you have any further questions, we recommend you submit a support ticket to our Support Team directly on our web site: [Submit a Support Ticket](https://supportcenter.devexpress.com/ask). This will help us to process your question more efficiently and you will receive a reply faster.
