### ISSUE TITLE
Does not work on Visual Studio Mac, JB Rider or Visual Studio Code

### ISSUE THREAD

**Issue by Tagwerk-Berlin** [DevExpress-Examples/Reporting-Blazor-Getting-Started#2]
I get always an Internal Server Error

**Comment by vasyaste** [comment]
Hello @Tagwerk-Berlin,

This error message indicates that something went wrong while running your report code on the web server. To determine what causes this issue, follow the steps described in the [Reporting Application Diagnostics](https://docs.devexpress.com/XtraReports/401687/web-reporting/general-information/application-diagnostics) help topic. Hope this information will help you determine an exact cause of the issue you faced.

In any case, if you have any further questions, we recommend you submit a support ticket to our Support Team directly on our web site: [Submit a Support Ticket](https://supportcenter.devexpress.com/ask). This will help us process your inquiry more efficiently and you will receive a reply faster.
