### ISSUE TITLE
Dynamic Data

### ISSUE THREAD

**Issue by Sathish9222** [DevExpress-Examples/Reporting-Blazor-Getting-Started#5]
Hi Team,
Can you let me know how to pass dynamic data to reports ? Thank you.

**Comment by vasyaste** [comment]
Hi @Sathish9222 ,

Please refer to the [Create Object Data Source at Runtime](https://docs.devexpress.com/XtraReports/401902/web-reporting/asp-net-core-reporting/document-viewer/bind-to-data/create-object-data-source-for-loaded-report) help topic to learn how to configure the report's data source at runtime dynamically in web applications. Similar code can be used in Blazor applications.

If you face any difficulties with this approach, feel free to contact our support team directly by [submitting a support ticket](https://supportcenter.devexpress.com/ticket/create).
