### ISSUE TITLE
Error when trying to populate the database

### ISSUE THREAD

**Issue by geraldmaale** [DevExpress-Examples/Reporting-Blazor-Getting-Started#6]
Hi,

This example works perfectly as demonstrated. However, if I choose to fetch data from database such as Northwind, I get error stating 'Error when trying to populate the datasource'.

In the Report designer using VS, the preview shows the data perfectly. But when using in the document viewer, the error is thrown. Note that the same procedures are followed in displaying the HelloWorld example. Just change the report to fetch the from database.

Is there any demo for fetching data from a database to display in a report or a way to resolve this?

Thanks.
![xpress report](https://user-images.githubusercontent.com/55647505/92300162-3c564200-ef8b-11ea-8b50-699cef9a93ee.png)

**Comment by vasyaste** [comment]
Hi @geraldmaale ,

The 'Error when trying to populate the datasource' error indicates that something went wrong while filling the report's data source. In any case, it is difficult to determine the exact cause of this problem without reviewing the real error message that was thrown by the database connection provider. To obtain this information follow the steps described in the [Reporting Application Diagnostics](https://docs.devexpress.com/XtraReports/401687/web-reporting/general-information/application-diagnostics) help topic. Hope the information received by using this approach will help you to nail down this issue.

P.S. If you have any further questions, we recommend you submit a support ticket to our Support Team directly on our web site: [Submit a Support Ticket](https://supportcenter.devexpress.com/ticket/create). This will help us to process your question more efficiently and you will receive a reply faster.
